---
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
  namespace: hello-api
  labels:
    app: nginx-reverse-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-reverse-proxy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
