{
 "title": "First Pane Of Glass (beyla)",
 "description": "One dashboard to rule them all\n\n- kubernetes\n- aws\n- splunk logs (mocked data)\n- SLOs\n- active alerts",
 "tags": [
  "kubernetes",
  "alerts",
  "slo",
  "beyla",
  "apm"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{k8s_cluster_name=\"$cluster\"},service_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{k8s_cluster_name=\"$cluster\", service_namespace=\"$namespace\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🔥 Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 } },
  { "title": "🎯 SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Availability SLI",
   "type": "stat",
   "description": "http!~5xx / total",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_request_duration_seconds_count{service_namespace=~\"$namespace\", service_name=~\"$service\", http_response_status_code!~\"5.*\"}[$__rate_interval] offset 2m\n        )\n    ) or 0 * sum(\n        rate(\n            http_server_request_duration_seconds_count{service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval] offset 2m\n        )\n    )\n) / sum(\n    rate(\n        http_server_request_duration_seconds_count{service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval] offset 2m\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLI",
   "type": "stat",
   "description": "request duration <= 2.5s",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_request_duration_seconds_bucket{service_namespace=~\"$namespace\", service_name=~\"$service\", http_response_status_code!~\"5..\", le=\"2.5\"}[$__rate_interval] offset 2m\n        )\n    ) or 0 * sum(\n        rate(\n            http_server_request_duration_seconds_bucket{service_namespace=~\"$namespace\", service_name=~\"$service\", le=\"2.5\"}[$__rate_interval] offset 2m\n        )\n    )\n) / ignoring (le) sum(\n    rate(\n        http_server_request_duration_seconds_count{service_namespace=~\"$namespace\", service_name=~\"$service\", http_response_status_code!~\"5..\"}[$__rate_interval] offset 2m\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "📈 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Success / Error rate",
   "type": "timeseries",
   "description": "HTTP status codes\n\nNOTE: What qualifies as \"success\" vs \"error\" really depends on each service own use of HTTP status codes. 2xx / (2xx + 5xx) is a good starting point.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\", http_response_status_code=~\"2.*\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\",}[$__rate_interval]\n    )\n)",
     "legendFormat": "2xx"
    },
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\", http_response_status_code=~\"3.*\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\",}[$__rate_interval]\n    )\n)",
     "legendFormat": "3xx"
    },
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\", http_response_status_code=~\"4.*\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\",}[$__rate_interval]\n    )\n)",
     "legendFormat": "4xx"
    },
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\", http_response_status_code=~\"5.*\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_request_duration_seconds_count{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\",}[$__rate_interval]\n    )\n)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request rate by route",
   "type": "timeseries",
   "description": "req/s",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (k8s_namespace_name, service_name, http_request_method, http_route) (rate(http_server_request_duration_seconds_count{k8s_namespace_name!=\"\", k8s_namespace_name=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "{{k8s_namespace_name}} / {{service_name}} {{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_request_duration_seconds_bucket{k8s_namespace_name=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network packets throughput/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$namespace\", pod=~\"$service-.*\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\", pod=~\"$service-.*\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$service-.*\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods status per namespace (last)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, phase) (kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$service-.*\"}) > 0",
     "legendFormat": "{{phase}} / {{namespace}}"
    }
   ]
  }
 ]
}