{
 "title": "First Pane Of Glass (otel)",
 "description": "One dashboard to rule them all\n\n- kubernetes\n- aws\n- splunk logs (mocked data)\n- SLOs\n- active alerts",
 "tags": [
  "kubernetes",
  "alerts",
  "slo",
  "apm",
  "otel"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{k8s_cluster_name=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(service_selector_labels{k8s_cluster_name=\"$cluster\", namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🔥 Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 } },
  { "title": "🎯 SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Availability SLI",
   "type": "stat",
   "description": "http!~5xx / total",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\", http_status_code!~\"5..\"}[$__rate_interval] offset 2m\n        )\n    ) or 0 * sum(\n        rate(\n            http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval] offset 2m\n        )\n    )\n) / sum(\n    rate(\n        http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval] offset 2m\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLI",
   "type": "stat",
   "description": "request duration <= 2.5s",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_duration_milliseconds_bucket{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\", http_status_code!~\"5..\", le=\"2500\"}[$__rate_interval] offset 2m\n        )\n    ) or 0 * sum(\n        rate(\n            http_server_duration_milliseconds_bucket{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\", le=\"2500\"}[$__rate_interval] offset 2m\n        )\n    )\n) / ignoring (le) sum(\n    rate(\n        http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\", http_status_code!~\"5..\"}[$__rate_interval] offset 2m\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "📈 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Success / Error rate",
   "type": "timeseries",
   "description": "HTTP status codes\n\nNOTE: What qualifies as \"success\" vs \"error\" really depends on each service own use of HTTP status codes. 2xx / (2xx + 5xx) is a good starting point.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\",  http_status_code=~\"2..\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n)",
     "legendFormat": "2xx"
    },
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\", http_status_code=~\"3..\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n)",
     "legendFormat": "3xx"
    },
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\", http_status_code=~\"4..\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n)",
     "legendFormat": "4xx"
    },
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\", http_status_code=~\"5..\"}[$__rate_interval]\n        )\n    ) or vector(0)\n) / sum(\n        rate(http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(\n    rate(\n        http_server_duration_milliseconds_bucket{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(\n    rate(\n        http_server_duration_milliseconds_bucket{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(\n    rate(\n        http_server_duration_milliseconds_bucket{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(\n    rate(\n        http_server_duration_milliseconds_bucket{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request rate by route",
   "type": "timeseries",
   "description": "req/s",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, http_method, http_target) (\n    rate(\n        http_server_duration_milliseconds_count{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n) > 0",
     "legendFormat": "{{job}} {{http_method}} {{http_target}}"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (\n    increase(\n        http_server_duration_milliseconds_bucket{k8s_cluster_name=~\"$cluster\", service_namespace=~\"$namespace\", service_name=~\"$service\"}[$__rate_interval]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network packets throughput/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$service-.*\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\", pod=~\"$service-.*\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$service-.*\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods status per namespace (last)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, phase) (kube_pod_status_phase{k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$service-.*\"}) > 0",
     "legendFormat": "{{phase}} / {{namespace}}"
    }
   ]
  },
  { "title": "📋 Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Warning and Errors",
   "type": "timeseries",
   "description": "per minute",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\", service_name=~\"$service\"} | detected_level =~ `(W|w)(arn|ARN).*|` [$__auto])) * 60",
     "legendFormat": "Warning"
    },
    {
     "direction": "backward",
     "expr": "sum(rate({namespace=~\"$namespace\", service_name=~\"$service\"} | detected_level=~`(E|e)(rror|RROR).*` [$__auto])) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Logs size in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "bytes_over_time({k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\", service_name=~\"$service\"}[$__range])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Logs count by service",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort_desc(sum by(service_name) (count_over_time({k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\", service_name=~\"$service\"}[$__range])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\", service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Cluster Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{\n  job=~\"integrations/kubernetes/eventhandler|infra-monitoring/eventrouter\",\n  k8s_cluster_name=~\"$cluster\", namespace=~\"$namespace\"\n}"
    }
   ]
  }
 ]
}