---
apiVersion: v1
kind: Pod
metadata:
  name: crash-loop
  namespace: noisy-neighborhood
spec:
  containers:
  - name: noisy-app
    image: python:3-slim
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    command: ["python3"]
    args: ["-c", "import sys; import time; print('Sleeping for 1m...'); time.sleep(60); print('Wake Up!'); sys.exit(1)"]
  terminationGracePeriodSeconds: 0
