---
apiVersion: v1
kind: Namespace
metadata:
  name: noisy-neighborhood
  labels:
    name: noisy-neighborhood
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-mem
  namespace: noisy-neighborhood
spec:
  containers:
  - name: noisy-app
    image: python:3-slim
    env:
    # Force the stdout and stderr streams to be unbuffered for easier logging
    - name: PYTHONUNBUFFERED
      value: "1"
    command: ["python3"]
    # Wait 5m to give any stale prom metrics time to clear, then run approx. 5m until OOM killed
    args: ["-c", "import time; print('Sleeping for 5m...'); time.sleep(300); print('Wake Up!'); [print(f'Allocating {i * 4} Mi...') or memory.append(bytearray(4 * 1024 * 1024)) or time.sleep(9.375) for i, memory in enumerate([[]]*1000)]"]
    resources:
      limits:
        memory: "128Mi"
      requests:
        memory: "64Mi"
  terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-cpu
  namespace: noisy-neighborhood
spec:
  containers:
  - name: noisy-app
    image: python:3-slim
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    command: ["python3"]
    args: ["-c", "import time; print('Sleeping for 5m...'); time.sleep(300); print('Wake Up!'); exec('while True: [i**i for i in range(1000)]')"]
    resources:
      limits:
        cpu: "0.2"
      requests:
        cpu: "0.1"
  terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: crash-loop
  namespace: noisy-neighborhood
spec:
  containers:
  - name: noisy-app
    image: python:3-slim
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    command: ["python3"]
    args: ["-c", "import sys; import time; print('Sleeping for 1m...'); time.sleep(60); print('Wake Up!'); sys.exit(1)"]
  terminationGracePeriodSeconds: 0
