---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
type: Opaque
stringData:
  # Default credentials - change these in production!
  rabbitmq-username: "admin"
  rabbitmq-password: "admin123"
  rabbitmq-erlang-cookie: "secretcookie123456789012345678901234567890"
